development:
  adapter: postgresql
  encoding: unicode
  database: scheduler_development
  pool: 5
  username: lucid
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: scheduler_test
  pool: 5
  username: lucid
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: scheduler_production
  pool: 5
  username: lucid
  password:
