development:
  adapter: postgresql
  encoding: unicode
  database: scheduler_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: scheduler_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: scheduler_production
  pool: 5
